version: '3.8'

services:
  backend:
    build:
      context: ./Nodejs-UsrMng-Mongo
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/user-management
    depends_on:
      - mongo

  frontend:
    build:
      context: ./UserMng/customer-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
